### ISSUE TITLE
rm not found on windows

### ISSUE THREAD

**Issue by shahidcodes** [dpjayasekara/baapan#9]
getting error with 
`'rm' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by dpjayasekara** [comment]
Thanks for reporting this. This is now fixed since `baapan@3.2.5`.

**Comment by dpjayasekara** [comment]
@shahidcodes Could you please update this ticket if you verify that `baapan` works fine on windows? https://github.com/dpjayasekara/baapan/issues/4
